In [47]:
#importing libraries
import numpy as np 
import pandas as pd
import seaborn as sns

data = pd.read_csv(r"D:\upes\3rd year\Application of ML in Industries\Lab\winequalityN.csv")
data.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [48]:
data.isnull().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [49]:
data.shape

(6497, 13)

In [50]:
data['fixed acidity'] = data['fixed acidity'].fillna(data['fixed acidity'].mean())
data['volatile acidity'] = data['volatile acidity'].fillna(data['volatile acidity'].mean())
data['citric acid'] = data['citric acid'].fillna(data['citric acid'].mode()[0])
data['residual sugar'] = data['residual sugar'].fillna(data['residual sugar'].mode()[0])
data['chlorides'] = data['chlorides'].fillna(data['chlorides'].mean())
data['pH'] = data['pH'].fillna(data['pH'].mean())
data['sulphates'] = data['sulphates'].fillna(data['sulphates'].mean())

In [51]:
X = data.iloc[:,1:12].values
y = data.iloc[:, -1].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [52]:
#preprocessing data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

"Logistic Regression": 

In [53]:
from sklearn.linear_model import LogisticRegression
classifier1 = LogisticRegression(random_state = 0,solver="liblinear")
classifier1.fit(X_train, y_train)
y_pred1 = classifier1.predict(X_test) 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [54]:
print("LOGISTIC REGRESSION")
cm1= confusion_matrix(y_test, y_pred1)
acc1 = accuracy_score(y_test, y_pred1)
print(cm1)
print(acc1)

LOGISTIC REGRESSION
[[  0   0   4   0   0   0   0]
 [  0   0  27  17   0   0   0]
 [  0   0 260 173   1   0   0]
 [  0   0 124 405  17   0   0]
 [  0   0  10 189  28   0   0]
 [  0   0   2  35   7   0   0]
 [  0   0   0   0   1   0   0]]
0.5330769230769231


"KNN" :

In [55]:
from sklearn.neighbors import KNeighborsClassifier
classifier2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier2.fit(X_train, y_train)

KNeighborsClassifier()

In [56]:
y_pred2 = classifier2.predict(X_test)

In [57]:
print("K-NEAREST NEIGHBOURS")
cm2= confusion_matrix(y_test, y_pred2)
acc2 = accuracy_score(y_test, y_pred2)
print(cm2)
print(acc2)

K-NEAREST NEIGHBOURS
[[  0   0   2   2   0   0   0]
 [  0   4  21  17   2   0   0]
 [  0  12 273 139  10   0   0]
 [  0   5 147 324  67   3   0]
 [  0   0  17 103 101   6   0]
 [  0   2   1  15  23   3   0]
 [  0   0   0   0   1   0   0]]
0.5423076923076923


"Naive_Bayes" :

In [58]:
from sklearn.naive_bayes import GaussianNB
classifier3 = GaussianNB()
classifier3.fit(X_train, y_train)
y_pred3 = classifier3.predict(X_test)

In [59]:
print("NAIVE BAYES")
cm3= confusion_matrix(y_test, y_pred3)
acc3 = accuracy_score(y_test, y_pred3)
print(cm3)
print(acc3)

NAIVE BAYES
[[  0   2   2   0   0   0   0]
 [  0   4  22  12   6   0   0]
 [  7  16 239 138  34   0   0]
 [  4  19 152 208 163   0   0]
 [  3   5  19  66 129   4   1]
 [  1   0   1  14  26   2   0]
 [  0   0   0   0   1   0   0]]
0.44769230769230767


"SVM" :

In [60]:
from sklearn.svm import SVC
classifier4 = SVC(kernel = 'rbf', random_state = 0)
classifier4.fit(X_train, y_train)
y_pred4 = classifier4.predict(X_test)

In [61]:
print("SUPPORT VECTOR MACHINE")
cm4= confusion_matrix(y_test, y_pred4)
acc4 = accuracy_score(y_test, y_pred4)
print(cm4)
print(acc4)

SUPPORT VECTOR MACHINE
[[  0   0   2   2   0   0   0]
 [  0   0  29  15   0   0   0]
 [  0   0 278 156   0   0   0]
 [  0   0 110 415  21   0   0]
 [  0   0   8 166  53   0   0]
 [  0   0   0  29  15   0   0]
 [  0   0   0   0   1   0   0]]
0.5738461538461539


"DECISION TREE":

In [62]:
from sklearn.tree import DecisionTreeClassifier
classifier5 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier5.fit(X_train, y_train)
y_pred5 = classifier5.predict(X_test)

In [63]:
print("DECISION TREE")
cm5= confusion_matrix(y_test, y_pred5)
acc5 = accuracy_score(y_test, y_pred5)
print(cm5)
print(acc5)

DECISION TREE
[[  0   2   1   1   0   0   0]
 [  0   9  25   6   4   0   0]
 [  3  15 290 106  20   0   0]
 [  4   8 112 335  76  11   0]
 [  1   0  12  76 129   9   0]
 [  0   1   6  14   7  16   0]
 [  0   0   0   0   1   0   0]]
0.5992307692307692
